language: elixir
elixir:
  - 1.0.4
  - 1.0.5
otp_release:
  - 17.5
  - 18.0
sudo: false
env:
  - MIX_ENV="test"
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - aforward@gmail.com
